-- CLIENTE
CREATE TABLE PIZZA_CLIENTE
(
 SEQCLIENTE NUMBER(9),
 NOME VARCHAR(60),
 ENDERECO VARCHAR2(30),
 BAIRRO VARCHAR2(30),
 TELEFONE VARCHAR2(11)
 );
ALTER TABLE PIZZA_CLIENTE ADD CONSTRAINT PIZZA_CLIENTEPK PRIMARY KEY(SEQCLIENTE);

-- TIPO PIZZA
CREATE TABLE PIZZA_TIPO
(
 SEQTIPO NUMBER(9),
 TIPO VARCHAR(60)
);
ALTER TABLE PIZZA_TIPO ADD CONSTRAINT PIZZA_TIPOPK PRIMARY KEY(SEQTIPO);

-- SABORES PIZZA
CREATE TABLE PIZZA_SABORES 
(
 SEQSABOR NUMBER(9),
 SABOR VARCHAR2(60),
 SEQTIPO NUMBER(9)
);
ALTER TABLE PIZZA_SABORES ADD CONSTRAINT PIZZA_SABORESPK PRIMARY KEY(SEQSABOR);
ALTER TABLE PIZZA_SABORES ADD CONSTRAINT PIZZA_SABORESFK FOREIGN KEY(SEQTIPO) REFERENCES PIZZA_TIPO(SEQTIPO);

-- PEDIDO 
CREATE TABLE PIZZA_PEDIDO
(
 SEQPEDIDO NUMBER(9),
 SEQCLIENTE NUMBER(9),
 SEQSABOR NUMBER(9),
 DTAPEDIDO DATE,
 QUANTIDADE NUMBER(5),
 TOTALPEDIDO NUMBER(9)
);
ALTER TABLE PIZZA_PEDIDO ADD CONSTRAINT PIZZA_PEDIDOPK PRIMARY KEY(SEQPEDIDO);
ALTER TABLE PIZZA_PEDIDO ADD CONSTRAINT PIZZA_PEDIDOFK1 FOREIGN KEY(SEQCLIENTE) REFERENCES PIZZA_CLIENTE(SEQCLIENTE);
ALTER TABLE PIZZA_PEDIDO ADD CONSTRAINT PIZZA_PEDIDOFK2 FOREIGN KEY(SEQSABOR) REFERENCES PIZZA_SABORES(SEQSABOR);
