-- CLIENTE
CREATE TABLE LOC_CLIENTE
(
 SEQCLIENTE NUMBER(9),
 NOME VARCHAR(60),
 CPF VARCHAR2(11),
 TELEFONE VARCHAR2(11)
);
ALTER TABLE LOC_CLIENTE ADD CONSTRAINT LOC_CLIENTEPK PRIMARY KEY (SEQCLIENTE);
CREATE SEQUENCE S_LOC_CLIENTE;

-- GENERO
CREATE TABLE LOC_GENERO
(
 SEQGENERO NUMBER(9),
 GENERO VARCHAR(60)
);
ALTER TABLE LOC_GENERO ADD CONSTRAINT LOC_GENEROPK PRIMARY KEY (SEQGENERO);
CREATE SEQUENCE S_LOC_GENERO;

-- FILME
CREATE TABLE LOC_FILME
(
 SEQFILME NUMBER(9),
 FILME VARCHAR2(60),
 SEQGENERO NUMBER(9)
);
ALTER TABLE LOC_FILME ADD CONSTRAINT LOC_FILMEPK PRIMARY KEY (SEQFILME);
ALTER TABLE LOC_FILME ADD CONSTRAINT LOC_FILMEFK1 FOREIGN KEY (SEQGENERO) REFERENCES LOC_GENERO(SEQGENERO); 
CREATE SEQUENCE S_LOC_FILME;

-- LOCACAO
CREATE TABLE LOC_LOCACAO
(
 SEQLOCACAO NUMBER(9),
 SEQCLIENTE NUMBER(9),
 SEQFILME NUMBER(9),
 DTALOCACAO DATE,
 DTADEVOLUCAO DATE
);
ALTER TABLE LOC_LOCACAO ADD CONSTRAINT LOC_LOCACAOPK PRIMARY KEY (SEQLOCACAO);
ALTER TABLE LOC_LOCACAO ADD CONSTRAINT LOC_LOCACAOFK1 FOREIGN KEY (SEQCLIENTE) REFERENCES LOC_CLIENTE(SEQCLIENTE); 
ALTER TABLE LOC_LOCACAO ADD CONSTRAINT LOC_LOCACAOFK2 FOREIGN KEY (SEQFILME) REFERENCES LOC_FILME(SEQFILME); 
CREATE SEQUENCE S_LOC_LOCACAO;


SELECT * FROM LOC_CLIENTE;
SELECT * FROM LOC_GENERO;
SELECT * FROM LOC_FILME;
SELECT * FROM LOC_LOCACAO;