
CREATE TABLE CADASTROPESSOA 
(
 CODIGO NUMBER(6),
 NOME VARCHAR2(100),
 EMAIL VARCHAR2(100),
 TELEFONE VARCHAR2(11)
 );
 
ALTER TABLE CADASTROPESSOA ADD CONSTRAINT CADASTROPESSOAPK PRIMARY KEY (CODIGO);
 
select * from CADASTROPESSOA